name: react-mapbox

on:
  push:
    branches:
      - master # default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # 如果配置 themeConfig.lastUpdated 为 false，则不需要添加该参数以加快检出速度
          fetch-depth:
            0
            # 安装 Node.js 和 pnpm
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22 # 选择你的 Node.js 版本

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: npm install

      - name: Build with dumi
        # 文档编译命令，如果是 react 模板需要修改为 npm run docs:build
        run: npm run docs:build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # 先去设置里面生成token 并打开相应权限， 再去项目的设置里面 生成secrets 并把gtoken填进去，把secrets的名字填到此处
          github_token: ${{ secrets.REACT_MAPBOXGL_ZT_SECRETS }}
          # 文档目录，如果是 react 模板需要修改为 docs-dist
          publish_dir: ./docs-dist
